/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthChatRouteImport } from './routes/_auth/chat'
import { Route as AuthChatIndexRouteImport } from './routes/_auth/chat/index'
import { Route as AuthChatSessionRouteImport } from './routes/_auth/chat/$session'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChatRoute = AuthChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatIndexRoute = AuthChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthChatRoute,
} as any)
const AuthChatSessionRoute = AuthChatSessionRouteImport.update({
  id: '/$session',
  path: '/$session',
  getParentRoute: () => AuthChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof AuthChatRouteWithChildren
  '/chat/$session': typeof AuthChatSessionRoute
  '/chat/': typeof AuthChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$session': typeof AuthChatSessionRoute
  '/chat': typeof AuthChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/chat': typeof AuthChatRouteWithChildren
  '/_auth/chat/$session': typeof AuthChatSessionRoute
  '/_auth/chat/': typeof AuthChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/chat/$session' | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$session' | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/chat'
    | '/_auth/chat/$session'
    | '/_auth/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/chat': {
      id: '/_auth/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat/': {
      id: '/_auth/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthChatIndexRouteImport
      parentRoute: typeof AuthChatRoute
    }
    '/_auth/chat/$session': {
      id: '/_auth/chat/$session'
      path: '/$session'
      fullPath: '/chat/$session'
      preLoaderRoute: typeof AuthChatSessionRouteImport
      parentRoute: typeof AuthChatRoute
    }
  }
}

interface AuthChatRouteChildren {
  AuthChatSessionRoute: typeof AuthChatSessionRoute
  AuthChatIndexRoute: typeof AuthChatIndexRoute
}

const AuthChatRouteChildren: AuthChatRouteChildren = {
  AuthChatSessionRoute: AuthChatSessionRoute,
  AuthChatIndexRoute: AuthChatIndexRoute,
}

const AuthChatRouteWithChildren = AuthChatRoute._addFileChildren(
  AuthChatRouteChildren,
)

interface AuthRouteChildren {
  AuthChatRoute: typeof AuthChatRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChatRoute: AuthChatRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
