name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true

      - run: vp install --frozen-lockfile

      - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        working-directory: packages/cli

      - run: vp run ready

      - run: npm publish --no-git-checks
        working-directory: packages/cli
